# Generated by Django 4.2 on 2024-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='qunatity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='HEQO6J77', max_length=10),
        ),
    ]
