# Generated by Django 4.2 on 2024-01-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_qunatity_orderdetail_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='qunatity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='7ZYPGVMP', max_length=10),
        ),
    ]
