# Generated by Django 4.2 on 2024-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartdetail_quantity_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='8494MH0D', max_length=10),
        ),
    ]
